# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1936d3e9dc39b4e8e78ee6e52710f780757255e8a97fa2b048a1a14eb97201bdf5c339e34e920ededddc479eae1da9240ebca7d6104e104d3bb99e85b2c659fb

test:
  secret_key_base: fdda20ea248115c898041ad1546d4646f5cd745b76d2b79f1b772cdc167a22d629cd5551a2cf588bd0d937a6ce80c6aac8af74b82de05c2e36d5a48e7ef0f932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
